# Generated by Django 2.0.7 on 2018-09-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e1', models.CharField(default='0000000', max_length=30)),
                ('e2', models.CharField(default='0000000', max_length=30)),
                ('e3', models.CharField(default='0000000', max_length=30)),
                ('e4', models.CharField(default='0000000', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='dashs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(default='0000000', max_length=30)),
                ('s2', models.CharField(default='0000000', max_length=30)),
                ('s3', models.CharField(default='0000000', max_length=30)),
                ('s4', models.CharField(default='0000000', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='dasht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(default='0000000', max_length=30)),
                ('t2', models.CharField(default='0000000', max_length=30)),
                ('t3', models.CharField(default='0000000', max_length=30)),
                ('t4', models.CharField(default='0000000', max_length=30)),
                ('t5', models.CharField(default='0000000', max_length=30)),
                ('t6', models.CharField(default='0000000', max_length=30)),
                ('t7', models.CharField(default='0000000', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('userflag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votespeaker', models.IntegerField()),
                ('votetable', models.IntegerField()),
                ('voteeval', models.IntegerField()),
            ],
        ),
    ]
