# Generated by Django 2.0.7 on 2018-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashe',
            name='e1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dashe',
            name='e2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dashe',
            name='e3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dashe',
            name='e4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dashs',
            name='s1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dashs',
            name='s2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dashs',
            name='s3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dashs',
            name='s4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dasht',
            name='t1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dasht',
            name='t2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dasht',
            name='t3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dasht',
            name='t4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dasht',
            name='t5',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dasht',
            name='t6',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dasht',
            name='t7',
            field=models.CharField(max_length=30),
        ),
    ]
