# Generated by Django 2.0.7 on 2018-09-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180908_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votespeaker', models.IntegerField()),
                ('voteevalu', models.IntegerField()),
                ('votetable', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='votess',
        ),
    ]
