# Generated by Django 2.0.7 on 2018-09-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_results'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='results',
            new_name='result',
        ),
    ]
